version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/var/www/html
    depends_on:
      - backend
 

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
 

