FROM golang:1.20-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Install nodemon
RUN apk add --no-cache npm \
    && npm install -g nodemon
RUN go build -o main .
# RUN go run .

EXPOSE 8080

CMD ["nodemon", "--exec", "go run .", "--signal", "SIGTERM"]

