name: CMR to IIS (Self-hosted)

on:
  push:
    branches:
      - master

jobs:
  deploy-project:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Composer dependencies
        shell: cmd
        run: |
          echo Installing Composer dependencies...
          cd %GITHUB_WORKSPACE%\frontend
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-scripts

      - name: Deploy project to IIS
        shell: cmd
        run: |
          set SOURCE=%GITHUB_WORKSPACE%
          set TARGET=D:\inetpub\wwwroot\CRM_DOCKER

          echo Cleaning files inside target folder but skipping 'frontend\assets\images\uploaded'...

          for /d %%i in ("%TARGET%\*") do (
              if /i not "%%~nxi"=="frontend" (
                  rmdir /s /q "%%i"
              ) else (
                  for /d %%j in ("%%i\*") do (
                      if /i not "%%~nxj"=="assets" (
                          rmdir /s /q "%%j"
                      ) else (
                          for /d %%k in ("%%j\*") do (
                              if /i not "%%~nxk"=="images" (
                                  rmdir /s /q "%%k"
                              ) else (
                                  for /d %%l in ("%%k\*") do (
                                      if /i not "%%~nxl"=="uploaded" (
                                          rmdir /s /q "%%l"
                                      )
                                  )
                              )
                          )
                      )
                  )
              )
          )

          for %%i in ("%TARGET%\*.*") do del /f /q "%%i"

          echo Copying all files but excluding frontend\assets\images\uploaded...
          robocopy "%SOURCE%" "%TARGET%" /E /Z /XD "%SOURCE%\frontend\assets\images\uploaded" || exit 0
