name: CMR to IIS (Self-hosted)

on:
  push:
    branches:
      - master

jobs:
  deploy-project:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Composer dependencies
        shell: cmd
        run: |
          echo Installing Composer dependencies...
          cd %GITHUB_WORKSPACE%\frontend
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-scripts

      - name: Deploy project to IIS
        shell: cmd
        run: |
          set SOURCE=%GITHUB_WORKSPACE%
          set TARGET=C:\inetpub\wwwroot\CRM_DOCKER

          echo Cleaning old files...
          if exist "%TARGET%" rmdir /s /q "%TARGET%"
          mkdir "%TARGET%"

          echo Copying all files but excluding frontend\assets\images\uploaded...
          robocopy "%SOURCE%" "%TARGET%" /E /Z /XD "%SOURCE%\frontend\assets\images\uploaded" || exit 0

